<Project>
    <PropertyGroup>
        <BaseIntermediateOutputPath>Build\obj\</BaseIntermediateOutputPath>
        <DefaultItemExcludes>$(DefaultItemExcludes);obj\**;Build\**;artifacts\**;MediaInfoKeeper-build\**</DefaultItemExcludes>
        <NuGetCacheVersion>20260408</NuGetCacheVersion>
    </PropertyGroup>
</Project>
